# Generated by Django 4.2.1 on 2023-05-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendsRelationship',
            new_name='Friendship',
        ),
    ]
